# Generated by Django 6.0 on 2025-12-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlembicVersion',
            fields=[
                ('version_num', models.CharField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'alembic_version',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurrentRosters',
            fields=[
                ('pk', models.CompositePrimaryKey('league_id', 'player_key', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'current_rosters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_key', models.CharField()),
                ('league_key', models.CharField(unique=True)),
                ('season', models.CharField()),
            ],
            options={
                'db_table': 'leagues',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matchups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_num', models.IntegerField()),
                ('matchup_index', models.IntegerField()),
            ],
            options={
                'db_table': 'matchups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField()),
            ],
            options={
                'db_table': 'player_positions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_key', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, null=True)),
                ('positions', models.CharField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'players',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RosterSlotsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('selected_position', models.CharField(blank=True, null=True)),
                ('had_game', models.BooleanField(blank=True, null=True)),
                ('gp', models.IntegerField()),
            ],
            options={
                'db_table': 'roster_slots_daily',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_id', models.IntegerField()),
                ('abbr', models.CharField(blank=True, null=True)),
                ('name', models.CharField(blank=True, null=True)),
                ('position_type', models.CharField(blank=True, null=True)),
                ('group_code', models.CharField(blank=True, null=True)),
                ('group_order', models.IntegerField(blank=True, null=True)),
                ('stat_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stat_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_key', models.CharField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'teams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlayerGp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_num', models.IntegerField()),
                ('gp', models.IntegerField()),
                ('source', models.CharField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weekly_player_gp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklyTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_num', models.IntegerField()),
                ('stat_id', models.IntegerField()),
                ('stat_abbr', models.CharField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weekly_totals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_num', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField()),
            ],
            options={
                'db_table': 'weeks',
                'managed': False,
            },
        ),
    ]
