"""Add value to stat_categories and add roster_requirements table

Revision ID: 05a5b2d67380
Revises: 37c566502d51
Create Date: 2026-01-02 08:47:18.710696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05a5b2d67380'
down_revision: Union[str, Sequence[str], None] = '37c566502d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roster_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=16), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'position', name='uq_roster_req_league_pos')
    )
    with op.batch_alter_table('stat_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stat_categories', schema=None) as batch_op:
        batch_op.drop_column('value')

    op.drop_table('roster_requirements')
    # ### end Alembic commands ###
