"""Add CurrentRoster table and player metadata

Revision ID: d92520fbdffe
Revises: 0002_add_stat_grouping
Create Date: 2025-12-22 11:14:37.045665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd92520fbdffe'
down_revision: Union[str, Sequence[str], None] = '0002_add_stat_grouping'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_rosters',
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('player_key', sa.String(length=64), nullable=False),
    sa.Column('team_key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_key'], ['players.player_key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_key'], ['teams.team_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('league_id', 'player_key')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('positions', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('last_synced', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('last_synced')
        batch_op.drop_column('positions')

    op.drop_table('current_rosters')
    # ### end Alembic commands ###
